name: "whisper_decoder"
platform: "onnxruntime_onnx"
max_batch_size: 1

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "last_hidden_state"
    data_type: TYPE_FP32
    dims: [-1, -1, 768]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [-1, -1, 51865]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]